// Generated by https://quicktype.io

// projectsData
export interface Board {
  id: number;
  name: string;
  columns: IColumn[];
}

export interface IColumn {
  id: number;
  name: string;
  tasks: ITask[];
}

export interface ITask {
  id: number;
  title: string;
  description: string;
  status: Status;
  statusId: number;
  subtasks: Subtask[];
}

export enum Status {
  Doing = "Doing",
  Done = "Done",
  Now = "Now",
  Todo = "Todo",
}

export interface Subtask {
  title: string;
  isCompleted: boolean;
}

// cardData
export interface Card {
  amount: number | null;
  categories: string[];
  transactions: ITransaction[];
}

export interface ITransaction {
  id: number;
  type: string;
  amount: number;
  date: string;
  category: string;
  notes: string;
}
