// Generated by https://quicktype.io

// projectsData
export interface Board {
    id:      number;
    name:    string;
    columns: Column[];
}

export interface Column {
    id:    number;
    name:  string;
    tasks: Task[];
}

export interface Task {
    id:          number;
    title:       string;
    description: string;
    status:      Status;
    statusId:    number;
    subtasks:    Subtask[];
}

export enum Status {
    Doing = "Doing",
    Done = "Done",
    Now = "Now",
    Todo = "Todo",
}

export interface Subtask {
    title:       string;
    isCompleted: boolean;
}


// cardData
export interface Card {
    amount:       number;
    categories:   string[];
    transactions: Transaction[];
}

export interface Transaction {
    id:       number;
    type:     string;
    amount:   number;
    date:     string;
    category: string;
    notes:    string;
}
