'use client'
import { useEffect } from "react";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import PrelineScript from "@/app/_components/PrelineScript";

import { ReduxProvider } from '@/app/_redux/provider'
import SidebarHeader from "./_components/del_SidebarHeader";
import Header from "./_components/shared/header/Header";
import Main from "./_components/shared/main/del_Main";
import Sidebar from "./_components/shared/sidebar/Sidebar";
import MainContent from "./_components/shared/main/MainContent";
import PrelineScript from "./_components/PrelineScript";
import SidebarToggle from "./_components/shared/sidebarToggle/SidebarToggle";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en ">
      <ReduxProvider>
      <body className={`${inter.className} bg-gray-50 dark:bg-slate-900 `}>
      <Header/>
       <SidebarToggle/>
       <Sidebar/>
<MainContent>
   {children}
</MainContent>
           
      
       
 
      
    
       </body>
       </ReduxProvider>
       <PrelineScript />
    </html>
  );
}
